### ISSUE TITLE
Add Sale Notification email for Vendors

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-custom-deliverables#15]
FES doesn't have a notification email for Vendors when their products sell. Custom Deliverables will require that in order to let Vendors know when they need to start working on producing the custom files for an order.

**Comment by mintplugins** [comment]
We've decided to add this to FES itself: 
https://github.com/easydigitaldownloads/edd-fes/issues/1336

**Comment by davidsherlock** [comment]
@mintplugins, this is why I mentioned having the ability to set which products are customizable so the email is only sent explicitly required.

**Comment by mintplugins** [comment]
@davidsherlock Right that makes sense.
