### ISSUE TITLE
Invalid argument supplied for foreach() on bundled products

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-custom-deliverables#17]
If the user purchases a bundled product, and you as the admin upload customized files, the following warning shows on the payment receipt:

`Warning: Invalid argument supplied for foreach() in /app/public/wp-content/plugins/edd-custom-deliverables/includes/functions/helper-functions.php on line 46`

**Comment by mintplugins** [comment]
Fixed in #20
