### ISSUE TITLE
Global email settings suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-custom-deliverables#2]
@mintplugins, this plugin caught my attention as I am actually building a Fiverr like marketplace using https://astoundify.com/products/private-messages/ and a custom bridge between EDD and this messaging plugin.

I have one suggestion however, it would be useful to have the ability to set a default email template in the settings and disable vendors (and possibility admins) from being able to send custom emails to maintain uniformity and standardization. It would could also have the option to automatically send the email once custom files are uploaded by either party (vendor or admin).

I have a few other suggestions I will post as separate github issues.

**Comment by mintplugins** [comment]
@davidsherlock It was actually originally coded that way. However, what about in a case where the customer is unhappy with the files and requests a change?

With it the way it is now, you could re-upload the deliverable and send an email saying something along the lines of "I have re-uploaded your files according to your request".

Thoughts?

**Comment by davidsherlock** [comment]
@mintplugins, see my reply on issue #3 and let me know your thoughts.

**Comment by mintplugins** [comment]
Emails are now global with separate ones for FES and Admin.
