### ISSUE TITLE
Undefined index 'view' in upload dir function

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-custom-deliverables#6]
[This line](https://github.com/easydigitaldownloads/edd-custom-deliverables/blob/master/includes/functions/misc-functions.php#L215) throws a PHP undefined index error for me on every page except the view payment page. Probably just need to check first to see if `view` exists before checking whether it is the correct value.

**Comment by mintplugins** [comment]
Thanks - fixed in master
